#!/usr/bin/env bash

alias vim="$VIM"
alias vims="NVIM_LISTEN_ADDRESS=/tmp/nvim $VIM"
alias la='exa -lar --icons'
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
alias project 'cd ~/project'
alias v=vim
alias vimrc="$VIM $HOME/.config/nvim/"

