local Remap = require("bad.keymap")
local nnoremap = Remap.nnoremap

nnoremap("<leader>fg", function()
    require('telescope.builtin').live_grep()
end)
nnoremap("<C-p>", function()
    require('telescope.builtin').git_files()
end)
nnoremap("<Leader>ff", function()
    require('telescope.builtin').find_files()
end)

nnoremap("<leader>fw", function()
    require('telescope.builtin').grep_string { search = vim.fn.expand("<cword>") }
end)
nnoremap("<leader>fb", function()
    require('telescope.builtin').buffers()
end)
nnoremap("<leader>fh", function()
    require('telescope.builtin').help_tags()
end)
nnoremap("<leader>h", function()
    require 'telescope'.extensions.file_browser.file_browser()
end)
