#!/usr/bin/env zsh

gsettings  set  org.gnome.desktop.peripherals.mouse  accel-profile  flat

# xinput --set-prop 20 200 1.2 0 0 0 1 0 0 0 1
#!/bin/bash

# Find the ID of "Logitech USB Receiver Mouse"
device_id=$(xinput list | grep "Logitech USB Receiver Mouse" | awk '{print $7}' | sed 's/id=//')

# Check if the device ID is found
if [ -n "$device_id" ]; then
    # Apply changes to entry 200
    xinput set-prop $device_id 200 1.2 0 0 0 1 0 0 0 1
fi
