#!/usr/bin/env zsh

gsettings  set  org.gnome.desktop.peripherals.mouse  accel-profile  flat

#!/bin/bash

# Find the ID of "Logitech USB Receiver Mouse"
device_id=$(xinput list | grep "Logitech USB Receiver Mouse" | awk '{print $7}' | sed 's/id=//')

# Check if the device ID is found
if [ -n "$device_id" ]; then
    # Find the ID of the sense property
    prop_id=$(xinput list-props $device_id | grep "Coordinate Transformation Matrix" | awk '{print $4}' | sed 's/(//' | sed 's/)://')

    # Check if the prop ID is found
    if [ -n "$prop_id" ]; then
        speed=0.8
        # Apply changes to entry prop
        xinput set-prop $device_id $prop_id 1 0 0 0 1 0 0 1
    fi
fi
