#!/usr/bin/env zsh

# Find the ID of "Logitech USB Receiver Mouse"
device_id=$(xinput list | grep "Logitech USB Receiver Mouse" | awk '{print $7}' | sed 's/id=//')

# Check if the device ID is found
if [ -n "$device_id" ]; then
    # Find the ID of the sense property
    sense_prop_id=$(xinput list-props $device_id | grep "Coordinate Transformation Matrix" | awk '{print $4}' | sed 's/(//' | sed 's/)://')

    # Check if the prop ID is found
    if [ -n "$sense_prop_id" ]; then
        echo "Found sense property and setting new value"
        # Apply changes to entry prop
        xinput set-prop $device_id $sense_prop_id 0.8 0 0 0 0.8 0 0 0 1
    fi

    # Find the ID of the accel property
    accel_prop_id=$(xinput list-props $device_id | grep "Accel Profile Enabled (" | awk '{print $5}' | sed 's/(//' | sed 's/)://')

    # Check if the prop ID is found
    if [ -n "$accel_prop_id" ]; then
        echo "Found accel property and setting flat profile"
        # Apply changes to entry prop
        xinput set-prop $device_id $accel_prop_id 0 1 0
    fi 
fi
