[env]
TERM = "xterm-256color"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.9

[window.padding]
x = 10
y = 15

[font]
size = 10.0

[font.bold]
family = "Hack Nerd Font Mono"
style = "Heavy"

[font.bold_italic]
family = "Hack Nerd Font Mono"
style = "Heavy Italic"

[font.italic]
family = "Hack Nerd Font Mono"
style = "Medium Italic"

[font.normal]
family = "Hack Nerd Font Mono"
style = "Medium"

[keyboard]
bindings = [
  { key = "Equals", mods = "Control", action = "IncreaseFontSize" },
  { key = "Minus", mods = "Control", action = "DecreaseFontSize" },
]
